project:
  type: website
  output-dir: docs

resources:
  - assets/icons/**
  - data/yale_library_data_listing.json
  - data/yale_library_data_listing.yml

website:
  title: ""
  search: false
  site-url: "https://yalelibrarydri.github.io/data-listing/"
  repo-url: "https://github.com/YaleLibraryDRI/data-listing"
  navbar:
    background: "#00356b"
    foreground: "#ffffff"
    logo: assets/yale-library-long.png
  page-footer:
    left: "Yale Library"
    right: "Built with Quarto"

format:
  html:
    anchor-sections: false
    theme:
      light: cosmo
    css:
      - assets/listing.css
    toc: false
    link-external-newwindow: true
